class TanzaniaLocations {
  static const Map<String, List<String>> regionsAndDistricts = {
    'Arusha Region': [
      'Arusha City',
      'Arusha District',
      'Karatu District',
      'Longido District',
      'Meru District',
      'Monduli District',
      'Ngorongoro District',
    ],
    'Dar es Salaam Region': [
      'Ilala Municipal',
      'Kigamboni Municipal',
      'Kinondoni Municipal',
      'Temeke Municipal',
      'Ubungo Municipal',
    ],
    'Dodoma Region': [
      'Bahi District',
      'Chamwino District',
      'Chemba District',
      'Dodoma Municipal',
      'Kondoa District',
      'Kondoa Town',
      'Kongwa District',
      'Mpwapwa District',
    ],
    'Geita Region': [
      'Bukombe District',
      'Chato District',
      'Geita District',
      'Geita Town',
      'Mbogwe District',
      'Nyang\'hwale District',
    ],
    'Iringa Region': [
      'Iringa District',
      'Iringa Municipal',
      'Kilolo District',
      'Mafinga Town',
      'Mufindi District',
    ],
    'Kagera Region': [
      'Biharamulo District',
      'Bukoba District',
      'Bukoba Municipal',
      'Karagwe District',
      'Kyerwa District',
      'Missenyi District',
      'Muleba District',
      'Ngara District',
    ],
    'Kaskazini Pemba Region': [
      'Micheweni District',
      'Wete District',
    ],
    'Kaskazini Unguja Region': [
      'Kaskazini A District',
      'Kaskazini B District',
    ],
    'Katavi Region': [
      'Mlele District',
      'Mpanda District',
      'Mpanda Municipal',
      'Mpimbwe District',
      'Nsimbo District',
    ],
    'Kigoma Region': [
      'Buhigwe District',
      'Kakonko District',
      'Kasulu District',
      'Kasulu Town',
      'Kibondo District',
      'Kigoma District',
      'Kigoma Ujiji District',
      'Uvinza District',
    ],
    'Kilimanjaro Region': [
      'Hai District',
      'Moshi District',
      'Moshi Municipal',
      'Mwanga District',
      'Rombo District',
      'Same District',
      'Siha District',
    ],
    'Kusini Pemba Region': [
      'Chake Chake District',
      'Mkoani District',
    ],
    'Kusini Unguja Region': [
      'Kati District',
      'Kusini District',
    ],
    'Lindi Region': [
      'Kilwa District',
      'Lindi District',
      'Lindi Municipal',
      'Liwale District',
      'Nachingwea District',
      'Ruangwa District',
    ],
    'Manyara Region': [
      'Babati District',
      'Babati Town',
      'Hanang District',
      'Kiteto District',
      'Mbulu District',
      'Mbulu Town',
      'Simanjiro District',
    ],
    'Mara Region': [
      'Bunda District',
      'Bunda Town',
      'Butiama District',
      'Musoma District',
      'Musoma Municipal',
      'Rorya District',
      'Serengeti District',
      'Tarime District',
      'Tarime Town',
    ],
    'Mbeya Region': [
      'Busokelo District',
      'Chunya District',
      'Kyela District',
      'Mbarali District',
      'Mbeya City',
      'Mbeya District',
      'Rungwe District',
    ],
    'Mjini Magharibi Region': [
      'Magharibi A District',
      'Magharibi B District',
      'Mjini District',
    ],
    'Morogoro Region': [
      'Gairo District',
      'Ifakara Town',
      'Kilombero District',
      'Kilosa District',
      'Malinyi District',
      'Morogoro District',
      'Morogoro Municipal',
      'Mvomero District',
      'Ulanga District',
    ],
    'Mtwara Region': [
      'Masasi District',
      'Masasi Town',
      'Mtwara District',
      'Mtwara Municipal',
      'Nanyamba District',
      'Nanyumbu District',
      'Newala District',
      'Newala Town',
      'Tandahimba District',
    ],
    'Mwanza Region': [
      'Buchosa District',
      'Ilemela Municipal',
      'Kwimba District',
      'Magu District',
      'Misungwi District',
      'Nyamagana Municipal',
      'Sengerema District',
      'Ukerewe District',
    ],
    'Njombe Region': [
      'Ludewa District',
      'Makambako Town',
      'Makete District',
      'Njombe District',
      'Njombe Town',
      'Wanging\'ombe District',
    ],
    'Pwani Region': [
      'Bagamoyo District',
      'Chalinze District',
      'Kibaha District',
      'Kibaha Town',
      'Kibiti Town',
      'Kisarawe District',
      'Mafia District',
      'Mkuranga District',
      'Rufiji District',
    ],
    'Rukwa Region': [
      'Kalambo District',
      'Nkasi District',
      'Sumbawanga District',
      'Sumbawanga Municipal',
    ],
    'Ruvuma Region': [
      'Madaba District',
      'Mbinga District',
      'Mbinga Town',
      'Namtumbo District',
      'Nyasa District',
      'Songea District',
      'Songea Municipal',
      'Tunduru District',
    ],
    'Shinyanga Region': [
      'Kahama Town',
      'Kishapu District',
      'Msalala District',
      'Shinyanga District',
      'Shinyanga Municipal',
      'Ushetu District',
    ],
    'Simiyu Region': [
      'Bariadi District',
      'Bariadi Town',
      'Busega District',
      'Itilima District',
      'Maswa District',
      'Meatu District',
    ],
    'Singida Region': [
      'Ikungi District',
      'Iramba District',
      'Itigi District',
      'Manyoni District',
      'Mkalama District',
      'Singida District',
      'Singida Municipal',
    ],
    'Songwe Region': [
      'Ileje District',
      'Mbozi District',
      'Momba District',
      'Songwe District',
      'Tunduma Town',
    ],
    'Tabora Region': [
      'Igunga District',
      'Kaliua District',
      'Nzega District',
      'Nzega Town',
      'Sikonge District',
      'Tabora Municipal',
      'Urambo District',
      'Uyui District',
    ],
    'Tanga Region': [
      'Bumbuli District',
      'Handeni District',
      'Handeni Town',
      'Kilindi District',
      'Korogwe District',
      'Korogwe Town',
      'Lushoto District',
      'Mkinga District',
      'Pangani District',
      'Tanga City',
    ],
  };

  static List<String> get allRegions => regionsAndDistricts.keys.toList();

  static List<String> getDistricts(String? region) {
    if (region == null || !regionsAndDistricts.containsKey(region)) {
      return [];
    }
    return regionsAndDistricts[region]!;
  }
}
